import type { LeaderboardEntry } from "@/lib/types";

export const mockLeaderboardSeason: LeaderboardEntry[] = [
  {
    rank: 1,
    memberId: "member-2",
    displayName: "Connor",
    teamName: "Bijan Mustard",
    faabBalance: 1050,
    seasonProfitLoss: 210,
    totalWagered: 640,
    betsWon: 11,
    betsLost: 6,
    winPercent: 65,
    largestWin: 92,
    currentStreak: "W3",
  },
  {
    rank: 2,
    memberId: "member-1",
    displayName: "Justin",
    teamName: "Hurts So Good",
    faabBalance: 742,
    seasonProfitLoss: 173,
    totalWagered: 580,
    betsWon: 10,
    betsLost: 7,
    winPercent: 59,
    largestWin: 78,
    currentStreak: "W2",
  },
  {
    rank: 3,
    memberId: "member-3",
    displayName: "Dave",
    teamName: "Puka Shells",
    faabBalance: 890,
    seasonProfitLoss: 95,
    totalWagered: 510,
    betsWon: 9,
    betsLost: 8,
    winPercent: 53,
    largestWin: 65,
    currentStreak: "L1",
  },
  {
    rank: 4,
    memberId: "member-5",
    displayName: "Mike",
    teamName: "The Last Air Bender",
    faabBalance: 705,
    seasonProfitLoss: 40,
    totalWagered: 470,
    betsWon: 8,
    betsLost: 8,
    winPercent: 50,
    largestWin: 55,
    currentStreak: "W1",
  },
  {
    rank: 5,
    memberId: "member-7",
    displayName: "Sam",
    teamName: "Diggs My Grave",
    faabBalance: 560,
    seasonProfitLoss: -95,
    totalWagered: 505,
    betsWon: 6,
    betsLost: 10,
    winPercent: 38,
    largestWin: 48,
    currentStreak: "L2",
  },
  {
    rank: 6,
    memberId: "member-4",
    displayName: "Ravi",
    teamName: "CeeDeez Nuts",
    faabBalance: 615,
    seasonProfitLoss: -140,
    totalWagered: 560,
    betsWon: 6,
    betsLost: 11,
    winPercent: 35,
    largestWin: 60,
    currentStreak: "L1",
  },
  {
    rank: 7,
    memberId: "member-6",
    displayName: "Alex",
    teamName: "Gibbs Me Liberty",
    faabBalance: 480,
    seasonProfitLoss: -280,
    totalWagered: 615,
    betsWon: 5,
    betsLost: 13,
    winPercent: 28,
    largestWin: 70,
    currentStreak: "L4",
  },
  {
    rank: 8,
    memberId: "member-8",
    displayName: "Tyler",
    teamName: "Zero Dark Thirty",
    faabBalance: 390,
    seasonProfitLoss: -320,
    totalWagered: 690,
    betsWon: 4,
    betsLost: 15,
    winPercent: 21,
    largestWin: 40,
    currentStreak: "L3",
  },
];

export const mockLeaderboardWeek: LeaderboardEntry[] = [
  {
    rank: 1,
    memberId: "member-3",
    displayName: "Dave",
    teamName: "Puka Shells",
    faabBalance: 890,
    seasonProfitLoss: 60,
    totalWagered: 70,
    betsWon: 2,
    betsLost: 0,
    winPercent: 100,
    largestWin: 45,
    currentStreak: "W2",
  },
  {
    rank: 2,
    memberId: "member-1",
    displayName: "Justin",
    teamName: "Hurts So Good",
    faabBalance: 742,
    seasonProfitLoss: 38,
    totalWagered: 50,
    betsWon: 1,
    betsLost: 0,
    winPercent: 100,
    largestWin: 38,
    currentStreak: "W1",
  },
  {
    rank: 3,
    memberId: "member-5",
    displayName: "Mike",
    teamName: "The Last Air Bender",
    faabBalance: 705,
    seasonProfitLoss: 15,
    totalWagered: 35,
    betsWon: 1,
    betsLost: 1,
    winPercent: 50,
    largestWin: 15,
    currentStreak: "W1",
  },
  {
    rank: 4,
    memberId: "member-7",
    displayName: "Sam",
    teamName: "Diggs My Grave",
    faabBalance: 560,
    seasonProfitLoss: -5,
    totalWagered: 20,
    betsWon: 0,
    betsLost: 1,
    winPercent: 0,
    largestWin: 0,
    currentStreak: "L1",
  },
  {
    rank: 5,
    memberId: "member-2",
    displayName: "Connor",
    teamName: "Bijan Mustard",
    faabBalance: 1050,
    seasonProfitLoss: -12,
    totalWagered: 40,
    betsWon: 0,
    betsLost: 1,
    winPercent: 0,
    largestWin: 0,
    currentStreak: "L1",
  },
  {
    rank: 6,
    memberId: "member-4",
    displayName: "Ravi",
    teamName: "CeeDeez Nuts",
    faabBalance: 615,
    seasonProfitLoss: -30,
    totalWagered: 30,
    betsWon: 0,
    betsLost: 1,
    winPercent: 0,
    largestWin: 0,
    currentStreak: "L2",
  },
  {
    rank: 7,
    memberId: "member-6",
    displayName: "Alex",
    teamName: "Gibbs Me Liberty",
    faabBalance: 480,
    seasonProfitLoss: -20,
    totalWagered: 25,
    betsWon: 0,
    betsLost: 1,
    winPercent: 0,
    largestWin: 0,
    currentStreak: "L4",
  },
  {
    rank: 8,
    memberId: "member-8",
    displayName: "Tyler",
    teamName: "Zero Dark Thirty",
    faabBalance: 390,
    seasonProfitLoss: -45,
    totalWagered: 45,
    betsWon: 0,
    betsLost: 1,
    winPercent: 0,
    largestWin: 0,
    currentStreak: "L3",
  },
];
