import type { FantasyPlayer, FantasyTeam } from "@/lib/types";

export const mockTeams: FantasyTeam[] = [
  {
    id: "roster-1",
    ownerMemberId: "975162996680945664",
    name: "Hurts So Good",
    logoEmoji: "🦅",
    record: { wins: 5, losses: 1, ties: 0 },
    pointsFor: 782.4,
    pointsAgainst: 651.2,
    recentForm: ["W", "W", "L", "W", "W"],
  },
  {
    id: "roster-2",
    ownerMemberId: "984151623574323200",
    name: "Bijan Mustard",
    logoEmoji: "🌭",
    record: { wins: 4, losses: 2, ties: 0 },
    pointsFor: 745.8,
    pointsAgainst: 702.1,
    recentForm: ["L", "W", "W", "L", "W"],
  },
  {
    id: "roster-3",
    ownerMemberId: "984156047625523200",
    name: "Puka Shells",
    logoEmoji: "🐚",
    record: { wins: 4, losses: 2, ties: 0 },
    pointsFor: 731.0,
    pointsAgainst: 690.4,
    recentForm: ["W", "W", "W", "L", "L"],
  },
  {
    id: "roster-4",
    ownerMemberId: "594590141419405312",
    name: "CeeDeez Nuts",
    logoEmoji: "🥜",
    record: { wins: 3, losses: 3, ties: 0 },
    pointsFor: 698.6,
    pointsAgainst: 704.9,
    recentForm: ["L", "L", "W", "W", "L"],
  },
  {
    id: "roster-5",
    ownerMemberId: "984230356897337344",
    name: "The Last Air Bender",
    logoEmoji: "🌪️",
    record: { wins: 3, losses: 3, ties: 0 },
    pointsFor: 712.3,
    pointsAgainst: 715.0,
    recentForm: ["W", "L", "L", "W", "L"],
  },
  {
    id: "roster-6",
    ownerMemberId: "987034877151293440",
    name: "Gibbs Me Liberty",
    logoEmoji: "🗽",
    record: { wins: 2, losses: 4, ties: 0 },
    pointsFor: 664.1,
    pointsAgainst: 733.7,
    recentForm: ["L", "L", "W", "L", "L"],
  },
  {
    id: "roster-7",
    ownerMemberId: "990743597525831680",
    name: "Diggs My Grave",
    logoEmoji: "⛏️",
    record: { wins: 2, losses: 4, ties: 0 },
    pointsFor: 671.9,
    pointsAgainst: 728.5,
    recentForm: ["W", "L", "L", "L", "W"],
  },
  {
    id: "roster-8",
    ownerMemberId: "990745711383805952",
    name: "Zero Dark Thirty",
    logoEmoji: "🌑",
    record: { wins: 1, losses: 5, ties: 0 },
    pointsFor: 612.5,
    pointsAgainst: 745.3,
    recentForm: ["L", "L", "L", "W", "L"],
  },
];

// Real rosters carry bench depth beyond the 9 starting slots. Odds are
// computed from each team's best-possible lineup across this full list (see
// getOptimalLineup in matchup-service.ts), not whatever a member has
// actually started — so benching a stud right before betting opens can't
// manufacture worse odds than the roster actually supports.
export const mockPlayersByTeam: Record<string, FantasyPlayer[]> = {
  "roster-1": [
    { id: "t1-qb1", name: "Jalen Hurts", position: "QB", nflTeam: "PHI", projectedPoints: 24.1 },
    { id: "t1-rb1", name: "Saquon Barkley", position: "RB", nflTeam: "PHI", projectedPoints: 21.3 },
    { id: "t1-rb2", name: "James Cook", position: "RB", nflTeam: "BUF", projectedPoints: 16.8 },
    { id: "t1-wr1", name: "A.J. Brown", position: "WR", nflTeam: "PHI", projectedPoints: 18.4 },
    { id: "t1-wr2", name: "DeVonta Smith", position: "WR", nflTeam: "PHI", projectedPoints: 14.2 },
    { id: "t1-te1", name: "Dallas Goedert", position: "TE", nflTeam: "PHI", projectedPoints: 11.6 },
    { id: "t1-flex1", name: "Rome Odunze", position: "WR", nflTeam: "CHI", projectedPoints: 12.9 },
    { id: "t1-k1", name: "Jake Elliott", position: "K", nflTeam: "PHI", projectedPoints: 8.1 },
    { id: "t1-def1", name: "Eagles D/ST", position: "DEF", nflTeam: "PHI", projectedPoints: 9.0 },
    { id: "t1-bench1", name: "Kenneth Walker III", position: "RB", nflTeam: "SEA", projectedPoints: 15.1 },
    { id: "t1-bench2", name: "Jordan Addison", position: "WR", nflTeam: "MIN", projectedPoints: 13.7 },
  ],
  "roster-2": [
    { id: "t2-qb1", name: "Jayden Daniels", position: "QB", nflTeam: "WAS", projectedPoints: 22.6 },
    { id: "t2-rb1", name: "Bijan Robinson", position: "RB", nflTeam: "ATL", projectedPoints: 19.9 },
    { id: "t2-rb2", name: "Chuba Hubbard", position: "RB", nflTeam: "CAR", projectedPoints: 14.1 },
    { id: "t2-wr1", name: "Terry McLaurin", position: "WR", nflTeam: "WAS", projectedPoints: 15.7 },
    { id: "t2-wr2", name: "Drake London", position: "WR", nflTeam: "ATL", projectedPoints: 13.8 },
    { id: "t2-te1", name: "Kyle Pitts", position: "TE", nflTeam: "ATL", projectedPoints: 9.4 },
    { id: "t2-flex1", name: "Jayden Reed", position: "WR", nflTeam: "GB", projectedPoints: 11.2 },
    { id: "t2-k1", name: "Younghoe Koo", position: "K", nflTeam: "ATL", projectedPoints: 7.6 },
    { id: "t2-def1", name: "Commanders D/ST", position: "DEF", nflTeam: "WAS", projectedPoints: 7.3 },
    { id: "t2-bench1", name: "Tyrone Tracy Jr.", position: "RB", nflTeam: "NYG", projectedPoints: 10.8 },
    { id: "t2-bench2", name: "Rashid Shaheed", position: "WR", nflTeam: "NO", projectedPoints: 10.1 },
  ],
  "roster-3": [
    { id: "t3-qb1", name: "C.J. Stroud", position: "QB", nflTeam: "HOU", projectedPoints: 21.8 },
    { id: "t3-rb1", name: "Joe Mixon", position: "RB", nflTeam: "HOU", projectedPoints: 15.9 },
    { id: "t3-rb2", name: "Rachaad White", position: "RB", nflTeam: "TB", projectedPoints: 13.4 },
    { id: "t3-wr1", name: "Puka Nacua", position: "WR", nflTeam: "LAR", projectedPoints: 19.1 },
    { id: "t3-wr2", name: "Nico Collins", position: "WR", nflTeam: "HOU", projectedPoints: 16.3 },
    { id: "t3-te1", name: "Sam LaPorta", position: "TE", nflTeam: "DET", projectedPoints: 12.4 },
    { id: "t3-flex1", name: "Tank Dell", position: "WR", nflTeam: "HOU", projectedPoints: 10.6 },
    { id: "t3-k1", name: "Ka'imi Fairbairn", position: "K", nflTeam: "HOU", projectedPoints: 8.4 },
    { id: "t3-def1", name: "Texans D/ST", position: "DEF", nflTeam: "HOU", projectedPoints: 8.2 },
    { id: "t3-bench1", name: "Jaylen Warren", position: "RB", nflTeam: "PIT", projectedPoints: 11.4 },
    { id: "t3-bench2", name: "Jayden Higgins", position: "WR", nflTeam: "HOU", projectedPoints: 9.5 },
  ],
  "roster-4": [
    { id: "t4-qb1", name: "Justin Herbert", position: "QB", nflTeam: "LAC", projectedPoints: 20.9 },
    { id: "t4-rb1", name: "J.K. Dobbins", position: "RB", nflTeam: "LAC", projectedPoints: 14.7 },
    { id: "t4-rb2", name: "Tony Pollard", position: "RB", nflTeam: "TEN", projectedPoints: 13.1 },
    { id: "t4-wr1", name: "CeeDee Lamb", position: "WR", nflTeam: "DAL", projectedPoints: 17.9 },
    { id: "t4-wr2", name: "Ladd McConkey", position: "WR", nflTeam: "LAC", projectedPoints: 13.5 },
    { id: "t4-te1", name: "Trey McBride", position: "TE", nflTeam: "ARI", projectedPoints: 13.2 },
    { id: "t4-flex1", name: "Calvin Ridley", position: "WR", nflTeam: "TEN", projectedPoints: 11.8 },
    { id: "t4-k1", name: "Cameron Dicker", position: "K", nflTeam: "LAC", projectedPoints: 7.9 },
    { id: "t4-def1", name: "Chargers D/ST", position: "DEF", nflTeam: "LAC", projectedPoints: 7.7 },
    { id: "t4-bench1", name: "Jaylen Warren", position: "RB", nflTeam: "PIT", projectedPoints: 11.9 },
    { id: "t4-bench2", name: "Jerry Jeudy", position: "WR", nflTeam: "CLE", projectedPoints: 10.3 },
  ],
  "roster-5": [
    { id: "t5-qb1", name: "Baker Mayfield", position: "QB", nflTeam: "TB", projectedPoints: 19.7 },
    { id: "t5-rb1", name: "Bucky Irving", position: "RB", nflTeam: "TB", projectedPoints: 16.2 },
    { id: "t5-rb2", name: "Javonte Williams", position: "RB", nflTeam: "DAL", projectedPoints: 12.6 },
    { id: "t5-wr1", name: "Mike Evans", position: "WR", nflTeam: "TB", projectedPoints: 14.9 },
    { id: "t5-wr2", name: "Chris Godwin", position: "WR", nflTeam: "TB", projectedPoints: 13.1 },
    { id: "t5-te1", name: "Cade Otton", position: "TE", nflTeam: "TB", projectedPoints: 8.7 },
    { id: "t5-flex1", name: "Jauan Jennings", position: "WR", nflTeam: "SF", projectedPoints: 10.4 },
    { id: "t5-k1", name: "Chase McLaughlin", position: "K", nflTeam: "TB", projectedPoints: 7.8 },
    { id: "t5-def1", name: "Buccaneers D/ST", position: "DEF", nflTeam: "TB", projectedPoints: 6.9 },
    { id: "t5-bench1", name: "Rachaad White", position: "RB", nflTeam: "TB", projectedPoints: 10.7 },
    { id: "t5-bench2", name: "Xavier Legette", position: "WR", nflTeam: "CAR", projectedPoints: 9.2 },
  ],
  "roster-6": [
    { id: "t6-qb1", name: "Jared Goff", position: "QB", nflTeam: "DET", projectedPoints: 19.3 },
    { id: "t6-rb1", name: "Jahmyr Gibbs", position: "RB", nflTeam: "DET", projectedPoints: 20.5 },
    { id: "t6-rb2", name: "David Montgomery", position: "RB", nflTeam: "DET", projectedPoints: 12.9 },
    { id: "t6-wr1", name: "Amon-Ra St. Brown", position: "WR", nflTeam: "DET", projectedPoints: 17.2 },
    { id: "t6-wr2", name: "Jameson Williams", position: "WR", nflTeam: "DET", projectedPoints: 11.5 },
    { id: "t6-te1", name: "Evan Engram", position: "TE", nflTeam: "DEN", projectedPoints: 9.8 },
    { id: "t6-flex1", name: "Josh Downs", position: "WR", nflTeam: "IND", projectedPoints: 9.9 },
    { id: "t6-k1", name: "Jake Bates", position: "K", nflTeam: "DET", projectedPoints: 8.0 },
    { id: "t6-def1", name: "Lions D/ST", position: "DEF", nflTeam: "DET", projectedPoints: 7.1 },
    { id: "t6-bench1", name: "Tyjae Spears", position: "RB", nflTeam: "TEN", projectedPoints: 10.2 },
    { id: "t6-bench2", name: "Wan'Dale Robinson", position: "WR", nflTeam: "NYG", projectedPoints: 9.3 },
  ],
  "roster-7": [
    { id: "t7-qb1", name: "Bo Nix", position: "QB", nflTeam: "DEN", projectedPoints: 18.6 },
    { id: "t7-rb1", name: "Kyren Williams", position: "RB", nflTeam: "LAR", projectedPoints: 15.4 },
    { id: "t7-rb2", name: "Najee Harris", position: "RB", nflTeam: "PIT", projectedPoints: 12.1 },
    { id: "t7-wr1", name: "Stefon Diggs", position: "WR", nflTeam: "HOU", projectedPoints: 13.6 },
    { id: "t7-wr2", name: "Courtland Sutton", position: "WR", nflTeam: "DEN", projectedPoints: 12.2 },
    { id: "t7-te1", name: "Dalton Kincaid", position: "TE", nflTeam: "BUF", projectedPoints: 9.1 },
    { id: "t7-flex1", name: "Romeo Doubs", position: "WR", nflTeam: "GB", projectedPoints: 9.7 },
    { id: "t7-k1", name: "Wil Lutz", position: "K", nflTeam: "DEN", projectedPoints: 7.5 },
    { id: "t7-def1", name: "Broncos D/ST", position: "DEF", nflTeam: "DEN", projectedPoints: 8.6 },
    { id: "t7-bench1", name: "Braelon Allen", position: "RB", nflTeam: "NYJ", projectedPoints: 9.6 },
    { id: "t7-bench2", name: "Khalil Shakir", position: "WR", nflTeam: "BUF", projectedPoints: 8.9 },
  ],
  "roster-8": [
    { id: "t8-qb1", name: "Caleb Williams", position: "QB", nflTeam: "CHI", projectedPoints: 17.9 },
    { id: "t8-rb1", name: "D'Andre Swift", position: "RB", nflTeam: "CHI", projectedPoints: 12.8 },
    { id: "t8-rb2", name: "Zack Moss", position: "RB", nflTeam: "CIN", projectedPoints: 10.9 },
    { id: "t8-wr1", name: "DJ Moore", position: "WR", nflTeam: "CHI", projectedPoints: 13.4 },
    { id: "t8-wr2", name: "Keenan Allen", position: "WR", nflTeam: "CHI", projectedPoints: 11.6 },
    { id: "t8-te1", name: "Cole Kmet", position: "TE", nflTeam: "CHI", projectedPoints: 7.9 },
    { id: "t8-flex1", name: "Tyler Boyd", position: "WR", nflTeam: "TEN", projectedPoints: 8.8 },
    { id: "t8-k1", name: "Cairo Santos", position: "K", nflTeam: "CHI", projectedPoints: 7.2 },
    { id: "t8-def1", name: "Bears D/ST", position: "DEF", nflTeam: "CHI", projectedPoints: 6.4 },
    { id: "t8-bench1", name: "Roschon Johnson", position: "RB", nflTeam: "CHI", projectedPoints: 7.4 },
    { id: "t8-bench2", name: "Cedric Tillman", position: "WR", nflTeam: "CLE", projectedPoints: 7.0 },
  ],
};
